name: Reporting service
project: reporting-service
workflow_file: reporting-entity.yml
execution:
  max_retries: 1
jobs:
  package:
    job_name: Package report
  verify:
    needs:
    - package
    job_name: Verify report
  preview:
    needs:
    - verify
    job_name: Deploy preview
recovery: {}
