name: Payment Service BDI-controlled CI/CD
project_file: payment_project.yaml
execution:
  max_retries: 1
jobs:
  build: {}
  test: {}
  security:
    needs: [build, test]
  staging:
    needs: [build, test, security]
  production:
    needs: staging
    observe_before: staging
